name: Pull Request Check # ì›Œí¬í”Œë¡œ ì´ë¦„

on: # ì›Œí¬í”Œë¡œ íŠ¸ë¦¬ê±° ì„¤ì •
  pull_request: # í’€ ë¦¬í€˜ìŠ¤íŠ¸ ì´ë²¤íŠ¸ì— ëŒ€í•´
    types: [opened, synchronize] # ì˜¤í”ˆ ë° ë™ê¸°í™” ì´ë²¤íŠ¸ì—ì„œ íŠ¸ë¦¬ê±°

jobs: # ì‘ì—… ì •ì˜
  check: # ì‘ì—… ì´ë¦„ check
    runs-on: ubuntu-latest # ìš°ë¶„íˆ¬ í™˜ê²½ì—ì„œ ì‹¤í–‰
    permissions: # ê¶Œí•œ ì„¤ì •
      pull-requests: write # í’€ ë¦¬í€˜ìŠ¤íŠ¸ì— ëŒ€í•œ ì“°ê¸° ê¶Œí•œ ì„¤ì •
    steps: # ì‘ì—… ë‹¨ê³„
      - uses: actions/github-script@v7 # GitHub ìŠ¤í¬ë¦½íŠ¸ ì•¡ì…˜ ì‚¬ìš©
        with: # ì˜µì…˜ ì„¤ì •
          script: | # ìŠ¤í¬ë¦½íŠ¸ ì‹œì‘
            const pull_request = context.payload.pull_request; # pull_request ê°ì²´ ê°€ì ¸ì˜¤ê¸°

            if (pull_request === undefined) { # pull_requestê°€ ì •ì˜ë˜ì§€ ì•Šì€ ê²½ìš°
                console.log("This is not a pull request"); # "This is not a pull request" ì¶œë ¥
                return; # ì¢…ë£Œ
            }

            const body = pull_request.body;

            if (!body) {
                // PRì— ì½”ë©˜íŠ¸ ì¶”ê°€.
                await github.rest.issues.createComment({ // PRì— ì½”ë©˜íŠ¸ ì¶”ê°€
                    owner: context.repo.owner, // ë¦¬í¬ì§€í† ë¦¬ ì†Œìœ ì
                    repo: context.repo.repo, // ë¦¬í¬ì§€í† ë¦¬ ì´ë¦„
                    issue_number: pull_request.number, // PR ë²ˆí˜¸
                    body: "ì´ PRì€ ê°€ì´ë“œë¼ì¸ì„ ì¤€ìˆ˜í•˜ì§€ ì•Šì•˜ìŠµë‹ˆë‹¤. ë”°ë¼ì„œ PRì„ ë‹«ê² ìŠµë‹ˆë‹¤. ê°€ì´ë“œë¼ì¸ì„ ì¤€ìˆ˜í•˜ê³  ë‹¤ë¥¸ PRì„ ìš”ì²­í•˜ì„¸ìš” ğŸ˜Š", // ì½”ë©˜íŠ¸ ë‚´ìš©
                });

                // PR ë‹«ê¸°.
                await github.rest.pulls.update({ // PR ë‹«ê¸°
                    owner: context.repo.owner, // ë¦¬í¬ì§€í† ë¦¬ ì†Œìœ ì
                    repo: context.repo.repo, // ë¦¬í¬ì§€í† ë¦¬ ì´ë¦„
                    pull_number: pull_request.number, // PR ë²ˆí˜¸
                    state: "closed", // ìƒíƒœë¥¼ ë‹«í˜ìœ¼ë¡œ ë³€ê²½
                });
            }
